### ISSUE TITLE
Project Import Error with VS2013 Update 4 and Cordova Tooling 0.3.1

### ISSUE THREAD

**Issue by lawrencegripper** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#10]
Got an error when loading the project related to not finding an import for Microsoft.MDA.targets.

Took the following two lines out:

``` XML
  <Import Project="$(AppData)\npm\node_modules\vs-mda-targets\Microsoft.MDA.targets" />
  <Import Project="$(AppData)\npm\node_modules\vs-mda-targets\Microsoft.TypeScript.MDA.targets" />
```

Replaced with their equivalents from a blank cordova project and all seemed to work well.

``` XML
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\CordovaTools\vs-mda-targets\Microsoft.MDA.targets" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\CordovaTools\vs-mda-targets\Microsoft.TypeScript.MDA.targets" />
```

Happy to put in a pull request with changes if you'd like?

**Comment by Justin-Credible** [comment]
I tested this on a refresh VM running Windows 10 Technical Preview (Build 10049) with a brand new install of VS2013 Community Edition Update 4 and Cordova CTP 0.3.1. I was able to reproduce the issue and after putting your change into place everything seemed to work fine.

I think I wasn't encountering this issue on my primary development machine because I had a previous version of the CTP installed, so the files were still located in the old location.

I will commit these changes shortly. Thanks for the feedback!
