### ISSUE TITLE
Failed to run on Android because of malformed manifest

### ISSUE THREAD

**Issue by IlieCiotir** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#55]
Hello,
I am trying to run the Sample-App on an android device. Installation fails with this message:

Total time: 11.678 secs
Built the following apk(s):
    D:\work\ionic\Test\Sample-App\platforms\android\build\outputs\apk\android-de
bug.apk
Using apk: D:\work\ionic\Test\Sample-App\platforms\android\build\outputs\apk\and
roid-debug.apk
Installing app on device...

D:\work\ionic\Test\Sample-App\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
ERROR: Failed to launch application on device: ERROR: Failed to install apk to d
evice:  pkg: /data/local/tmp/android-debug.apk

Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED]

ERROR running one or more of the platforms: Error: cmd: Command failed with exit
 code 1
You may not have the required environment or OS to run this project

I have tried with an ionic starting template and it works fine. 

It looks a lot like this issue: http://stackoverflow.com/questions/21716933/android-studio-install-parse-failed-manifest-malformed

The fixes there didn't seem to have any effect.

Anyone else having this issue?

**Comment by Justin-Credible** [comment]
When did you pull down the code? This should have been fixed yesterday in commit b5d155dd41a423544b5c5e897492059a2010395e.

**Comment by IlieCiotir** [comment]
Definitely before that! :) I'll sync and try again.

**Comment by IlieCiotir** [comment]
I can confirm that it works. 
The commit you linked has a lot of changes, is there any one of them in particular that fixes this issue?
I have a project already started based on the Sample-App and I'd rather not have to merge everything into it. :)

**Comment by Justin-Credible** [comment]
Unfortunately the short answer is no, there isn't a small change that fixed this.

The longer answer is that the problem was caused by some thing that changed in the Visual Studio Cordova template between the RC and RTM. In order to fix this, I had to File > New a new project and then integrate my starter project back into it. Along the way I found several issues which kind of snowballed into a large multi-fix commit (default plugins use the npm names instead of the old Cordova plugin registry names which lead to issues with Cordova 5.1.1 etc etc).

If you can't or don't want to try to migrate your changes into a new base starter project, I would suggest the File > New Project and copy your changes in approach, but know that you might run into the same issues I did.

Hope this helps!

**Comment by IlieCiotir** [comment]
That is indeed unfortunate.
Thanks for the help I'll see what I can do about it. :)
