### ISSUE TITLE
File access not working (add help text to dev tools)

### ISSUE THREAD

**Issue by alexangas** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#56]
None of the file system tests on the Development Tools page work. It looks like `config.xml` is missing the Cordova file plugin.

I tried adding it with the line `<vs:plugin name="cordova-plugin-file" version="2.1.0" />` in config.xml but still had problems. Clicking "List Files" logged this to the console:

TypeError: Wrong type for parameter "uri" of resolveLocalFileSystemURI: Expected String, but got Null.
    at TypeError (native)
    at Object.checkArgs (http://localhost:4400/cordova.js:427:15)
    at module.exports.resolveLocalFileSystemURL (http://localhost:4400/plugins/cordova-plugin-file/www/resolveLocalFileSystemURI.js:46:15)
    at FileUtilities.getDirectoryPaths (http://localhost:4400/scripts/appBundle.js:2953:28)
    at http://localhost:4400/scripts/appBundle.js:1921:45
    at http://localhost:4400/lib/ionic/js/ionic.bundle.min.js:143:20
    at l.$get.l.$eval (http://localhost:4400/lib/ionic/js/ionic.bundle.min.js:156:305)
    at l.$get.l.$digest (http://localhost:4400/lib/ionic/js/ionic.bundle.min.js:153:398)
    at l.$get.l.$apply (http://localhost:4400/lib/ionic/js/ionic.bundle.min.js:157:58)
    at HTMLButtonElement.<anonymous> (http://localhost:4400/lib/ionic/js/ionic.bundle.min.js:388:5695) undefined

Any ideas?

**Comment by Justin-Credible** [comment]
You are correct; I did remove the `cordova-file-plugin` from the default starter project. I did this because if the plugin is installed for Android projects it will request permissions to the file system. The only thing that used the file plugin functionality was the logging system, and while sometimes useful, this may not be worth the tradeoff of requiring your users to accept the file permissions when installing your application.

Because of this I changed the default logging behavior to be in-memory only which allows the developer to change this if they wish.

This is one of those things that is hard to strike a balance between; this is a starter project so I don't want to include too much functionality and dictate how you write your app, but I want to include enough base functionality that makes it useful as a starter.

So, with that said, yes, you'll need to add the file plugin if you want that functionality. This is one of those things that needs to be documented in the wiki, but I haven't had time to. I could quickly make a change to the developer tools view that lets the user know they need the file plugin installed to use those features.

**Comment by alexangas** [comment]
That all makes sense. I agree that something requiring permissions that may never be used should not be part of a starter project! A message in the developer tools view would be fine I think.

I'll keep hunting what the error I have is and report back if it might be in FileUtilities.ts.

**Comment by Justin-Credible** [comment]
Cool, I'll update the description of this issue to be for adding a message to the developer tools.

As for your issue, I've found that simply adding a `vs:plugin` element in `config.xml` isn't enough for Visual Studio. You need to actually go through the `config.xml` designer GUI with the project open and add the plugin there. I've found that the designer does some extra work when it pulls down the plugin (IIRC it adds a json file to the plugin directory in addition to updating `config.xml`).

**Comment by Justin-Credible** [comment]
Now that I'm looking at it, there is already code in `FileUtilities.ts` on each method that checks to see if `resolveLocalFileSystemURL` is available:

```
        if (typeof(window.resolveLocalFileSystemURL) === "undefined") {
            q.reject(new Error("window.resolveLocalFileSystemURL was not available; ensure that the Cordova file plugin (cordova-plugin-file) is installed properly."));
            return q.promise;
        }
```

From the stack trace you provided, it appears that the method exists, but is failing when called.

What platform are you on? It almost sounds like #11 where the `externalDataDirectory` isn't present on Windows Phone platforms.

**Comment by alexangas** [comment]
That call stack was from Ripple (sorry forgot to mention earlier). I've also tried the VS Android emulator and got an empty "Alert" box (because it couldn't fire up the console plugin). I also tried re-testing with the File plugin removed and re-added as you suggested.

**Comment by alexangas** [comment]
More testing in Ripple and I'm finding something that might be related to #53.

With `<script src="cordova.js"></script>` present in `index.html`, the function `$ionicPlatform.ready` is not called. From what I've read, this is necessary for the file plugin to initialise. The console shows:

> deviceready has not fired after 5 seconds.
> Channel not fired: onFileSystemPathsReady

Then with that script line commented out, `$ionicPlatform.ready` **is** called but the `cordova` global has not been initialised by the time we reach that function. :dizzy_face:

**Comment by Justin-Credible** [comment]
I started over with a clean clone of the repo into an empty directory. I was able to verify the Ionic platform ready event does fire (I verified by placing an `alert` statement) in the following platforms: iOS, Android, Windows Phone, Windows x64, and in browser via Ripple.

Since this issue has kind of turned into a few different things, I hope you don't mind if I close it since the original issue is now resolved-- I've modified the help message in the developer tools to let the developer know the plugin needs to be installed, and verified that using the `FileUtilities` methods throw a rejection promise with the name of the plugin as well.

If you continue to experience issues perhaps you can try a clean clone of the code (a lot has been changing lately) as well as enter brand new issues for the specific problems you are having.

**Comment by alexangas** [comment]
Just to close the loop on this, the final issue I had can be repro'd by downloading the project, adding the cordova file plugin, and debugging with Ripple. This doesn't occur in the VS emulator, so the problem is with Ripple and/or Chrome.
