### ISSUE TITLE
Use let and const

### ISSUE THREAD

**Issue by alexangas** [Justin-Credible/Ionic-TypeScript-MDHA-Starter#60]
In TypeScript 1.5 support for `let` and `const` [was added](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript). Replacing var with these keywords may be worthwhile from a "best practices" perspective, particularly due to the [problems with var](https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/). The ES5 output for let is `var` but the TypeScript compiler appears to follow the stricter behaviour of let.

Happy to submit a PR if you want to do this.

**Comment by Justin-Credible** [comment]
Good suggestion.

I too have thought about this and hesitated in making the change because it seemed like a lot of work with little return since I am already taking advantage of a tslint rule which would cause the following block to show a lint error:

```
x = 32;

for (var x = 10; x < 20; x++) {
    console.log(x);
}
```

Using `let` would be better as it would be a compile error rather than a lint error.

Though if you have already done this work, I definitely would consider accepting a pull request!

**Comment by Justin-Credible** [comment]
Also, a lot of code was written before I took advantage of the tslint rule, so several areas I put all of my var declarations at the top of the functions. It would be nice to refactor these and declare them where they are used instead of at the top.

**Comment by alexangas** [comment]
Sure. Is this something that is better done in the sister project or it doesn't matter?

**Comment by Justin-Credible** [comment]
Closing this for now since it conflicts with all of the restructuring to sync up with the sister project.

While I do think `let` is preferable to using `var`, I would rather keep the source in sync at this point.
